### PR TITLE
AcInputs load graph on side panel should be zero-centered

### LINKED ISSUE #1073: Brief page: Side panel grid graph fill
The grid graph should be filled to zero and not to the bottom.

Reference to https://github.com/victronenergy/gui-v2/pull/1065#issuecomment-2117300315

## Current
331313346-3e162f39-dc4d-4d6a-a0b4-99ce8ba27d31

## Expectation
331313847-1aace12c-ad3f-4a8d-a602-26d34f491da1

### PR DESCRIPTION
**Pull request by chriadam**
Grid draw should be shown in blue above the midpoint (zero amps) dotted line, and grid feed-in should be shown in green below the midpoint dotted line.

Fixes #1073

### CODE REVIEW

**Comment by mr-manuel** [comment]
Looks now much better!

**Comment by jpetrell** [comment]
Code LGTM. For feed-in case I could only see tiny amplitudes out of the graphs both on the GX device and on the mock mode, are you sure the limits are correct?

image

**Review by blammit — APPROVED** [review]
Nice, looks great!

**Comment by chriadam** [comment]
> Ah had 10A and -40A limits, maybe the asymmetry there was the reason. In such case would display the limit line on 1/5 of the graph height and not on the exact vertical center to utilize the space efficiently.

I do like the idea of utilising the range limits to determine the zero-line offset, but I asked Matthijs about this in the meeting and he said that for now we should just use the vertical center, that every install will be different and have different expectations, and using the center as the zero line will be clearest.  I might have misunderstood what he meant, of course!

**Comment by DanielMcInnes** [comment]
> I do like the idea of utilising the range limits to determine the zero-line offset, but I asked Matthijs about this in the meeting and he said that for now we should just use the vertical center, that every install will be different and have different expectations, and using the center as the zero line will be clearest. I might have misunderstood what he meant, of course!

That's how I remember it.

**Review by jpetrell — APPROVED** [review]

**Pull request merged**
