### PR TITLE
Access controls from top

### PR DESCRIPTION
**Pull request by jpetrell**
Fixes https://github.com/victronenergy/gui-v2/issues/574.

### CODE REVIEW

**Comment by jpetrell** [comment]
Showed the design to Serj. Updated the animation duration and easing curve to match the design. Qt doesn't have easing curve called ease-in, but chose Easing.InSine as that seemed close to the CSS ease-in.

**Comment by blammit** [comment]
@jpetrell could you add the task number to the commit please? Something like "Issue: #xxx" or "Fixes #xxx" as the last line would be sufficient.

**Review by blammit — DISMISSED** [review]

**Review by blammit — APPROVED** [review]
As discussed, noticed a minor issue where buttons in the control cards will change color when the cards begin to slide back upwards. Otherwise LGTM.

**Comment by jpetrell** [comment]
Fixed the focus flicker.

**Pull request merged**
