### PR TITLE
PageAlternator: add additional Alternators

### PR DESCRIPTION
**Pull request by nmbath**
https://github.com/victronenergy/gui-v2/issues/786

### CODE REVIEW

**Comment by nmbath** [comment]
@blammit Requested by Martin to assign this to you.

**Comment by jpetrell** [comment]
LGTM, though there is merge conflict.

**Review by blammit — APPROVED** [review]
LGTM also.

**Comment by nmbath** [comment]
@blammit would you like me to fix the merge issue and re-submit. Seems I did not work on the freshest branch.

**Comment by blammit** [comment]
> @blammit would you like me to fix the merge issue and re-submit. Seems I did not work on the freshest branch.

Yes, please :)

**Pull request closed without merging**
