### PR TITLE
Fix PageSettingsFroniusInverters uids

### PR DESCRIPTION
**Pull request by MikeTrahearn-Qinetic**
Use [bindPrefix + "/Inverters" in all cases.

### CODE REVIEW

**Comment by blammit** [comment]
@MikeTrahearn-Qinetic There are many uids related to fronius inverters, so "Fix PageSettingsFroniusInverters uids" is not very useful as a commit message - can you explain what issue this is fixing? In this case, it is fixing the list of uids for showing the list of Fronius inverters on the system, and specifically, the change ensures that the list appears as expected in mock mode.

**Comment by MikeTrahearn-Qinetic** [comment]
Commit message updated as requested. Force Pushed changes successfully after rebase on main.

**Comment by DanielMcInnes** [comment]
@MikeTrahearn-Qinetic is there an installation where I can test this?

**Comment by MikeTrahearn-Qinetic** [comment]
The only one we have presently is Izak Cerbo VRM but it isn't responding on my machine here.

**Review by DanielMcInnes — APPROVED** [review]

**Pull request merged**
