### PR TITLE
Make Tailscale login link clickable

### PR DESCRIPTION
**Pull request by mr-manuel**
This allows to click on the login URL in the WASM build.

### CODE REVIEW

**Comment by DanielMcInnes** [comment]
Hi Mr Manuel, I can't remember how to test tailscale features. I think you told me how last time?

**Comment by mr-manuel** [comment]
Hi @DanielMcInnes no problem. You can install it with this command: https://github.com/mr-manuel/venus-os_TailscaleGX?tab=readme-ov-file#install

Make sure, you have the latest Venus OS release candidate installed.

**Review by DanielMcInnes — APPROVED** [review]
lgtm. Tested ok, clicking on the link works in wasm builds, although the mouse icon doesn't change to the 'pointing' icon that you typically see when the mouse is over a hyperlink. Would that be easy to do?

**Comment by blammit** [comment]
> lgtm. Tested ok, clicking on the link works in wasm builds, although the mouse icon doesn't change to the 'pointing' icon that you typically see when the mouse is over a hyperlink. Would that be easy to do?

I think we'd need to hook into `onLinkHovered` and prompt the browser to change the icon with some state flag. Probably a bit finicky and something we can add later.

**Pull request merged**
