### PR TITLE
Fix invisible time-to-go

### LINKED ISSUE #768: Battery page: Time to go not visible
The time to go is not visible on the battery page, even if the item is present and valid.

https://github.com/victronenergy/gui-v2/blob/7873e22993e976916ca45489fe18023920e02694/pages/settings/devicelist/battery/PageBattery.qml#L182-L186

Probably because there is no `dataItem` in this case.

### PR DESCRIPTION
**Pull request by jpetrell**
Fixes #768.

### CODE REVIEW

**Comment by jpetrell** [comment]
PR https://github.com/victronenergy/gui-v2/pull/775

**Comment by jpetrell** [comment]
Checked that gui v1 and gui v2 showed the same values. gui v1 additionally had "show: item.seen" (VeQItem::getSeen()) visibility check, wonder if we should add the same for gui v2 also.

**Comment by mr-manuel** [comment]
Yes, I would also add item.seem since not every battery provides this value.

**Review by blammit — COMMENTED** [review]
Yes, we should keep the `seen` reference. The bug here is that `dataItem.uid` was not set to the `/TimeToGo` path.

**Review by blammit — APPROVED** [review]

**Pull request merged**
