### PR TITLE
Add QR code to Tailscale page

### PR DESCRIPTION
**Pull request by mr-manuel**
Enable QR code on Tailscale page after https://github.com/victronenergy/gui-v2/issues/1350#issuecomment-2330715682 was solved.

### CODE REVIEW

**Comment by mr-manuel** [comment]
Tested. The QR code seems a bit unsharp on a bigger screen. Should be ok on a normal GX device screen.

Bildschirmfoto am 2024-09-16 um 15 58 50

grafik

**Comment by DanielMcInnes** [comment]
> Tested. The QR code seems a bit unsharp on a bigger screen. Should be ok on a normal GX device screen.
> 
> Bildschirmfoto am 2024-09-16 um 15 58 50
> 
> grafik

@mr-manuel , if you change sourceSize.width and sourceSize.height to match actual width & height, the QR code becomes sharp

**Comment by DanielMcInnes** [comment]
This all works nicely once tailscale is installed via `curl -s https://raw.githubusercontent.com/mr-manuel/venus-os_TailscaleGX/main/download-and-install.sh | bash`. However, if tailscale is not installed, the user is stuck on this screen:

image


The message just says 'Starting...', there is nothing to indicate that it will never start because tailscale is not installed.
How is this meant to work? In the future, will tailscale be installed by default via firmware update?

**Comment by mr-manuel** [comment]
The Tailscale entry should not be shown, if you don‘t have Tailscale installed. This service still being integrated in Venus OS and will be installed by default in the future.

https://github.com/victronenergy/gui-v2/blob/398edf6103f9d41a3aa933a286dc797d66672bce/pages/settings/PageSettingsServices.qml#L29-L42

**Comment by mr-manuel** [comment]
> @mr-manuel , if you change sourceSize.width and sourceSize.height to match actual width & height, the QR code becomes sharp
How do I achieve that, since the GUI is scaled? In the source code the QR code should always be 200x200 but is upscaled if the GUI has more space.

**Comment by DanielMcInnes** [comment]
> > @mr-manuel , if you change sourceSize.width and sourceSize.height to match actual width & height, the QR code becomes sharp
> > How do I achieve that, since the GUI is scaled? In the source code the QR code should always be 200x200 but is upscaled if the GUI has more space.

Just make it 200x200, and it will be fine

**Comment by mr-manuel** [comment]
Fixed, thanks. You can merge it.

**Review by DanielMcInnes — APPROVED** [review]

**Pull request merged**
