### PR TITLE
MQTT: refactor the producer as a finite state machine

### PR DESCRIPTION
**Pull request by chriadam**
Contributes to issue #1385

### CODE REVIEW

**Comment by chriadam** [comment]
I'm hoping that this one fixed #1298 also.

**Comment by DanielMcInnes** [comment]
This doesn't fix #1298, but lgtm

image

**Review by DanielMcInnes — APPROVED** [review]

**Comment by chriadam** [comment]
Updated.  Now it also fixes #1298 as per Daniel's updated testing.

**Review by blammit — APPROVED** [review]

**Comment by DanielMcInnes** [comment]
There's a big switch case statement without a `default` case. Maybe a warning message?

```
/home/dmcinnes/git/victron/gui-v2/src/veutil/src/qt/ve_qitems_mqtt.cpp: In member function ‘bool VeQItemMqttProducer::isValidStateTransition(VeQItemMqttProducer::ConnectionState, VeQItemMqttProducer::ConnectionState) const’:
/home/dmcinnes/git/victron/gui-v2/src/veutil/src/qt/ve_qitems_mqtt.cpp:217:1: warning: control reaches end of non-void function [-Wreturn-type]
  217 | }
```

**Comment by chriadam** [comment]
Thanks, fixed.

**Pull request merged**
